version: '2'
services:
    sie-app:
        image: sie
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://sie-postgresql:5432/sie
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sie-postgresql:
        extends:
            file: postgresql.yml
            service: sie-postgresql
