version: '2'
services:
    statistical_operations_external-postgresql:
        image: postgres:9.6.2
        environment:
            - POSTGRES_USER=statistical_operations_external
            - POSTGRES_PASSWORD=statistical_operations_external
            - POSTGRES_DB=statistical_operations_external-dev
        ports:
            - 5432:5432
